Replace "if then return 1" with koi::die

diff --git a/koi b/koi
--- a/koi
+++ b/koi
@@ -144,6 +144,15 @@ function koi::verifyfiletype {
 }
 
 # ============ META FUNCTIONS ============ #
+function koi::die() {
+    local msg="$1"
+    local code="${2-1}"
+
+    koi::errortext -c "$koiname: $msg"
+    exit "$code"
+}
+
+
 function koi::commanddocs {
     local __stdout __stderr __helpoutput __cmd
     __helpoutput=
@@ -193,18 +202,18 @@ function koi::addarg {
 		$7 - the function used to verify the argument (optional)
 	COMMENT
 
-    if [[ $# -ne 6 && $# -ne 7 ]] ; then koi::errortext -c "$koiname: koi::addarg err: incorrect usage, either 6 or 7 arguments are required" ; return 1 ; fi
+     [[ $# -ne 6 && $# -ne 7 ]] && koi::die "koi::addarg err: incorrect usage, either 6 or 7 arguments are required" 1
 
     # short option
     if [[ "$1" != "" ]] ; then
-        if [[ "$1" != -* || "$1" == --* ]] ; then koi::errortext -c "$koiname: koi::addarg err: short option must start with a single dash" ; return 1 ; fi
-        if [[ "${#1}" -gt 2 ]] ; then koi::errortext -c "$koiname: koi::addarg err: short options must be a single dash followed by a single letter" ; return 1 ; fi
-        if [[ "$1" == *" "* ]] ; then koi::errortext -c "$koiname: koi::addarg err: short option cannot contain a space" ; return 1 ; fi
-        if ! [[ "$1" =~ ^-[a-zA-Z] ]] ; then koi::errortext -c "$koiname: koi::addarg err: short option must be a letter" ; return 1 ; fi
+         [[ "$1" != -* || "$1" == --* ]] && koi::die "koi::addarg err: short option must start with a single dash" 1
+         [[ "${#1}" -gt 2 ]] && koi::die "koi::addarg err: short options must be a single dash followed by a single letter" 1
+         [[ "$1" == *" "* ]] && koi::die "koi::addarg err: short option cannot contain a space" 1
+         ! [[ "$1" =~ ^-[a-zA-Z] ]] && koi::die "koi::addarg err: short option must be a letter" 1
     fi
 
     # long option
-    if [[ "$2" == "" ]] ; then koi::errortext -c "$koiname: koi::addarg err: missing long option for argument" ; return 1 ; fi
+     [[ "$2" == "" ]] && koi::die "koi::addarg err: missing long option for argument" 1
     if [[ "$3" == "positionalvalue" || "$3" == "positionalarray" ]] ; then
         if ! [[ "$2" =~ ^[a-zA-Z]+[a-zA-Z0-9]*$ ]] ; then
             koi::errortext -c "$koiname: koi::addarg err: positional arguments must be alphanumeric and cannot start with a number"
@@ -220,7 +229,7 @@ function koi::addarg {
             return 1
         fi
     fi
-    if [[ "$2" == *" "* ]] ; then koi::errortext -c "$koiname: koi::addarg err: long option cannot contain a space" ; return 1 ; fi
+     [[ "$2" == *" "* ]] && koi::die "koi::addarg err: long option cannot contain a space" 1
     local __illegalnames __illegalname
     __illegalnames=( \
         BASH BASH_ENV BASH_SUBSHELL BASHPID BASH_VERSINFO BASH_VERSION CDPATH \
@@ -242,46 +251,46 @@ function koi::addarg {
     # action
     local __availableactions
     __availableactions=( help storevalue storearray positionalvalue positionalarray flag )
-    if [[ "$3" == "" ]] ; then koi::errortext -c "$koiname: koi::addarg err: missing action for argument" ; return 1 ; fi
+     [[ "$3" == "" ]] && koi::die "koi::addarg err: missing action for argument" 1
     local __found __action
     __found=0
     for __action in "${__availableactions[@]}" ; do if [[ "$__action" == "$3" ]] ; then __found=1 ; break ; fi ; done
-    if [[ $__found -eq 0 ]] ; then koi::errortext -c "$koiname: koi::addarg err: action must be one of: $(__tmp=$(koi::join ',' "${__availableactions[@]}") ; echo "${__tmp//,/, }")" ; return 1 ; fi
+     [[ $__found -eq 0 ]] && koi::die "koi::addarg err: action must be one of: $(__tmp=$(koi::join ',' "${__availableactions[@]}") ; echo "${__tmp//,/, }")" 1
     if [[ "$3" == "positionalvalue" || "$3" == "positionalarray" ]] ; then
-        if [[ "$1" != "" ]] ; then koi::errortext -c "$koiname: koi::addarg err: positional arguments cannot have a short name" ; return 1 ; fi
-        if [[ "$2" == -* ]] ; then koi::errortext -c "$koiname: koi::addarg err: positional arguments long name cannot begin with a dash" ; return 1 ; fi
+         [[ "$1" != "" ]] && koi::die "koi::addarg err: positional arguments cannot have a short name" 1
+         [[ "$2" == -* ]] && koi::die "koi::addarg err: positional arguments long name cannot begin with a dash" 1
     fi
     if [[ "$3" == "help" ]] ; then
-        if [[ "$1" != "-h" ]] ; then koi::errortext -c "$koiname: koi::addarg err: help actions must use '-h' for their short names" ; return 1 ; fi
-        if [[ "$2" != "--help" ]] ; then koi::errortext -c "$koiname: koi::addarg err: help actions must use '--help' for their long names" ; return 1 ; fi
+         [[ "$1" != "-h" ]] && koi::die "koi::addarg err: help actions must use '-h' for their short names" 1
+         [[ "$2" != "--help" ]] && koi::die "koi::addarg err: help actions must use '--help' for their long names" 1
     fi
 
     # required
-    if [[ "$4" == "" ]] ; then koi::errortext -c "$koiname: koi::addarg err: missing required for argument" ; return 1 ; fi
-    if [[ "$4" != "required" && "$4" != "optional" ]] ; then koi::errortext -c "$koiname: koi::addarg err: required must be one of: required, optional" ; return 1 ; fi
-    if [[ "$3" == "help" && "$4" == "required" ]] ; then koi::errortext -c "$koiname: koi::addarg err: help option cannot be required" ; return 1 ; fi
+     [[ "$4" == "" ]] && koi::die "koi::addarg err: missing required for argument" 1
+     [[ "$4" != "required" && "$4" != "optional" ]] && koi::die "koi::addarg err: required must be one of: required, optional" 1
+     [[ "$3" == "help" && "$4" == "required" ]] && koi::die "koi::addarg err: help option cannot be required" 1
 
     # default
     if [[ "$5" != "" ]] ; then
-        if [[ "$4" == "required" ]] ; then koi::errortext -c "$koiname: koi::addarg err: required arguments cannot have default values" ; return 1 ; fi
-        if [[ "$3" == "help" ]] ; then koi::errortext -c "$koiname: koi::addarg err: help action cannot have a default value" ; return 1 ; fi
-        if [[ "$3" == "flag" ]] ; then koi::errortext -c "$koiname: koi::addarg err: flags cannot have default values" ; return 1 ; fi
-        if [[ "$3" == "storearray" ]] ; then koi::errortext -c "$koiname: koi::addarg err: arrays cannot have default values" ; return 1 ; fi
-        if [[ "$3" == "positionalvalue" ]] ; then koi::errortext -c "$koiname: koi::addarg err: positional values cannot have default values" ; return 1 ; fi
-        if [[ "$3" == "positionalarray" ]] ; then koi::errortext -c "$koiname: koi::addarg err: positional arrays cannot have default values" ; return 1 ; fi
+         [[ "$4" == "required" ]] && koi::die "koi::addarg err: required arguments cannot have default values" 1
+         [[ "$3" == "help" ]] && koi::die "koi::addarg err: help action cannot have a default value" 1
+         [[ "$3" == "flag" ]] && koi::die "koi::addarg err: flags cannot have default values" 1
+         [[ "$3" == "storearray" ]] && koi::die "koi::addarg err: arrays cannot have default values" 1
+         [[ "$3" == "positionalvalue" ]] && koi::die "koi::addarg err: positional values cannot have default values" 1
+         [[ "$3" == "positionalarray" ]] && koi::die "koi::addarg err: positional arrays cannot have default values" 1
     fi
 
     # help
-    if [[ "$6" == "" ]] ; then koi::errortext -c "$koiname: koi::addarg err: missing help text for argument" ; return 1 ; fi
+     [[ "$6" == "" ]] && koi::die "koi::addarg err: missing help text for argument" 1
 
     # verifyingfunction
     if [[ "$7" != "" ]] ; then
         local __verifyingcmd __verifyingargs
         __verifyingcmd="${7%% *}"
         __verifyingargs="${7##$__verifyingcmd}"
-        if ! declare -F -- "$__verifyingcmd" >/dev/null ; then koi::errortext -c "$koiname: koi::addarg err: specified verifying function '$7' is not defined" ; return 1 ; fi
-        if [[ "$3" == "help" ]] ; then koi::errortext -c "$koiname koi::addarg err: help options cannot have a verifyingfunction" ; return 1 ; fi
-        if [[ "$3" == "flag" ]] ; then koi::errortext -c "$koiname koi::addarg err: flag options cannot have a verifyingfunction" ; return 1 ; fi
+         ! declare -F -- "$__verifyingcmd" >/dev/null && koi::die "koi::addarg err: specified verifying function '$7' is not defined" 1
+         [[ "$3" == "help" ]] && koi::die "$koiname koi::addarg err: help options cannot have a verifyingfunction" 1
+         [[ "$3" == "flag" ]] && koi::die "$koiname koi::addarg err: flag options cannot have a verifyingfunction" 1
     fi
 
     # update argument lists
